//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsEquipmentManagement.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProduct
    {
        public int Id { get; set; }
        public string MaterialID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Inventory { get; set; }
        public string ImagePath { get; set; }
        public string SupplierCompany { get; set; }
    }
}
