//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsEquipmentManagement.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPO
    {
        public int Id { get; set; }
        public string PONumber { get; set; }
        public string Buyer { get; set; }
        public string Supplier { get; set; }
        public string BuyerUserID { get; set; }
        public string BuyerUserEmail { get; set; }
        public string PurchaseItemNameList { get; set; }
        public string PurchaseItemquantityList { get; set; }
        public string PurchaseItempriceList { get; set; }
        public Nullable<float> Totalamount { get; set; }
    }
}
